name: files
on:
  push:
    paths:
      - "**"
      - ".github/workflows/files.yml"
      
defaults:
  run:
    working-directory: ./
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip'
      - run: pip install .[dev]
      - run: python -m ruff .
      - run: python -m mypy --strict .
  test:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip'
      - run: pip install -e .[dev]
      - run: coverage run -m pytest -vv tests/
      - run: coverage report | grep 'TOTAL' | awk '{print "COVERAGE_PCT=" $4}' >> $GITHUB_ENV
      # TODO: publish coverage report